- .dockerignore
- Dockerfile
- docker-compose.yml
build(#3) Add docker-file and docker-compose in order to deploy member-page.
> Issue(#3) dockerfile

- backend/migrator/migrations/20201109135642_fix-contraints.js
- backend/services/members/Dockerfile
- backend/services/members/codegen.yml
- backend/services/members/graphql.schema.json
- backend/services/members/package-lock.json
- backend/services/members/package.json
- backend/services/members/src/db.ts
- backend/services/members/src/index.ts
- backend/services/members/src/resolvers.ts
- backend/services/members/src/schema.graphql
- backend/services/members/src/types/graphql.ts
- backend/services/members/src/types/mysql.ts
- backend/shared/src/database.ts
Depends on #44 
I've implemented graphql-codegen for the 'members' service and it seems like a good idea to move to this for all services.
> Graphql codegen backend

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
Change the default templates to be better fitted to this repository.
> Update issue templates 

- backend/services/members/src/types/graphql.ts
- frontend/src/api/members.graphql
- frontend/src/generated/graphql.tsx
> bugfix(#64): added picture path to frontend api

- backend/services/members/src/resolvers.ts
- backend/services/news/src/db.ts
Also fixed member resolver. Now removes typename from Member before returning object.
> Import statement news

- backend/services/news/package-lock.json
- backend/services/news/src/db.ts
- backend/services/news/src/resolvers.ts
- backend/services/news/src/typeDefs.ts
> feature(#67): Add pagination to news service

- backend/services/news/package-lock.json
- backend/services/news/src/db.ts
- backend/services/news/src/resolvers.ts
- backend/services/news/src/typeDefs.ts
- frontend/src/api/news.graphql
- frontend/src/components/Body.tsx
- frontend/src/generated/graphql.tsx
> bugfix news pagination

- backend/migrator/seeds/data.js
> bugfux(#89): Fix seed file

- backend/gateway/src/gateway.ts
Closes #95 
Fixes user context serializing bug
> bugfix(#95) fixes bug with serializing context

- backend/services/news/src/db.ts
> bugfix(#98): Fixes missing } in db.ts

- backend/services/members/src/datasources/Member.ts
> bugfix(#109): Fix getMemberFromKeycloakId

- backend/services/members/graphql.schema.json
- backend/services/members/package-lock.json
- backend/services/members/src/datasources/Member.ts
- backend/services/members/src/resolvers.ts
- backend/services/members/src/schema.graphql
- backend/services/members/src/types/graphql.ts
- backend/services/members/src/types/mysql.ts
- backend/services/members/tests/member.spec.ts
- backend/services/members/tests/mutations.spec.ts
- backend/services/members/tests/queries.spec.ts
> feature(#49): Add mutations and queries for members service

- .editorconfig
> feature(#121): Add an .editorconfig for more consistent code formatting

- frontend/components/Header/index.tsx
- frontend/components/Navigation/NavigationItems.tsx
- frontend/components/News/article.tsx
- frontend/routes.ts
- frontend/tsconfig.json
Adds routes.ts with strings for all routes.
> refactor(#120) adds single source for routes

- frontend/providers/LoginProvider.tsx
> bugfix(#132): Change keycloak url to new address

- .github/workflows/build.calendar.yml
- backend/services/calendar/package-lock.json
- backend/services/calendar/package.json
- backend/services/calendar/src/index.ts
- backend/services/calendar/src/server.ts
- backend/services/calendar/tests/event.spec.ts
- backend/services/calendar/tests/mutations.spec.ts
- backend/services/calendar/tests/queries.spec.ts
- backend/services/calendar/tests/util.ts
> tests(#116): Add tests to calendar service

- backend/gateway/package.json
- backend/services/calendar/Dockerfile.prod
- backend/services/calendar/package.json
- backend/services/calendar/tsconfig.build.json
- backend/services/core/Dockerfile.prod
- backend/services/core/package.json
- backend/services/core/tsconfig.build.json
- backend/services/news/Dockerfile.prod
- backend/services/news/package.json
- backend/services/news/tsconfig.build.json
- backend/shared/package-lock.json
- backend/shared/package.json
> bugfix(#136): Fix build setup

- frontend/api/news.graphql
- frontend/components/News/article.tsx
- frontend/components/News/articleSet.tsx
- frontend/generated/graphql.tsx
English versions of articles are now displayed if they exist.
Closes #149
> feature(#149): Adds english articles to frontend

- backend/services/calendar/package-lock.json
- backend/services/calendar/package.json
- backend/services/core/package-lock.json
- backend/services/core/package.json
- backend/services/news/package-lock.json
- backend/services/news/package.json
Supposed to migrate from graphql-import to graphql-tools but truns out graphql-import was not used to simply removes 
Closes #155
> refactor(#155): Removed unused dependency

- backend/services/calendar/package-lock.json
- backend/services/calendar/src/datasources/Events.ts
> bugfix(#140): Fix event filtering

- backend/docker-compose.minio.yml
- backend/migrator/package-lock.json
- backend/migrator/package.json
- backend/migrator/src/migrator.js
> feature(#165): Add migration for buckets in minio

- backend/migrator/migrations/20201021155159_create-core-tables.js
- backend/migrator/seeds/data.js
- backend/services/core/graphql.schema.json
- backend/services/core/package-lock.json
- backend/services/core/src/datasources.ts
- backend/services/core/src/datasources/Mandate.ts
- backend/services/core/src/resolvers.ts
- backend/services/core/src/schema.graphql
- backend/services/core/src/types/graphql.ts
- backend/services/core/src/types/mysql.ts
- backend/services/core/tests/mandate.spec.ts
- backend/services/core/tests/mutations.spec.ts
- backend/services/core/tests/queries.spec.ts
- backend/services/core/tests/util.ts
> feature(#38): Add mandates api

- backend/gateway/package-lock.json
- backend/gateway/package.json
- backend/gateway/src/gateway.ts
> bugfix(#52): Keycloak token gets verified

- backend/gateway/package-lock.json
- backend/migrator/package-lock.json
- backend/services/booking/package-lock.json
- backend/services/calendar/package-lock.json
- backend/services/core/package-lock.json
- backend/services/members/package-lock.json
- backend/services/news/package-lock.json
- frontend/package-lock.json
- frontend/package.json
> build(#180): update package-lock files

- backend/files/nginx.conf
- backend/migrator/src/migrator.js
- docker-compose.minio.yml
> feature(#198): update and set exact relase for minio

- backend/services/core/graphql.schema.json
- backend/services/core/src/datasources/Committee.ts
- backend/services/core/src/datasources/Position.ts
- backend/services/core/src/resolvers.ts
- backend/services/core/src/schema.graphql
- backend/services/core/src/types/graphql.ts
- backend/services/core/tests/committee.spec.ts
- backend/services/core/tests/mutations.spec.ts
- backend/services/core/tests/position.spec.ts
- backend/services/core/tests/queries.spec.ts
> feature(#97): Update core mutation return types

- backend/gateway/Dockerfile.prod
- backend/migrator/Dockerfile.prod
- backend/services/booking/Dockerfile.prod
- backend/services/calendar/Dockerfile.prod
- backend/services/core/Dockerfile.prod
- backend/services/news/Dockerfile.prod
- frontend/Dockerfile.prod
> refactor(#205): reduce the amount of layers in production docker files

- backend/files/nginx.conf
- docker-compose.minio.yml
> refactor(243): restructure minio to only use one host

- docker-compose.dev.yml
- docker-compose.minio.yml
- docker-compose.prod.yml
> bugfix(#248): make mino use volume in development

- .eslintrc.json
- README.md
- docker-compose.deploy.yml
- docker-compose.prod.yml
- frontend/generated/graphql.tsx
- frontend/pages/api/door/[doorName].ts
- frontend/pages/index.tsx
- frontend/providers/GraphQLProvider.tsx
- package-lock.json
- package.json
> feature(#182): add door endpoint att /api/door/[doorName]

- frontend/pages/404.tsx
> feature(#268): Adds a 404 page

- backend/migrator/migrations/20211205231900_add_columns_needed_for_migration_of_old_data.js
- backend/services/core/graphql.schema.json
- backend/services/core/package-lock.json
- backend/services/core/src/datasources/Committee.ts
- backend/services/core/src/datasources/Member.ts
- backend/services/core/src/datasources/Position.ts
- backend/services/core/src/schema.graphql
- backend/services/core/src/types/database.ts
- backend/services/core/src/types/graphql.ts
- backend/services/core/tests/committee.spec.ts
- backend/services/core/tests/mandate.spec.ts
- backend/services/core/tests/position.spec.ts
> feature(#273): add columns needed for old data migration

- backend/migrator/migrations/20211205231900_add_columns_needed_for_migration_of_old_data.js
- backend/services/core/src/datasources/Member.ts
- backend/services/core/tests/member.spec.ts
- frontend/pages/onboarding.tsx
> feature(#277): fixes adding new members to db

- backend/services/core/src/datasources/Position.ts
- frontend/pages/documents/index.tsx
> bug(#280): check that user can list inactive postitions

- frontend/components/Footer/index.tsx
- frontend/components/layout.tsx
- frontend/providers/MeilisearchProvider.tsx
- frontend/public/locales/en/common.json
- frontend/public/locales/sv/common.json
- frontend/styles/pageStyles.ts
> feature(#283): adds a footer

- frontend/components/Calendar/BigCalendar/Toolbar.tsx
Closes #305
Feel free to squash & merge if approved.
> (feature: #305) Move controllers for day/week/month

- frontend/components/Navigation/ListItemSet.tsx
- frontend/components/Navigation/listItems/ListItemDropdown.tsx
> (bugfix #292) Fix no menu access items causing extra padding

- frontend/components/Header/components/DarkModeSelector.tsx
- frontend/next-env.d.ts
> (feature #301) Change light/darkmode icons

- backend/gateway/Dockerfile
- backend/gateway/Dockerfile.prod
- backend/gateway/package-lock.json
- backend/gateway/package.json
- backend/gateway/src/gateway.ts
- backend/services/booking/Dockerfile
- backend/services/booking/Dockerfile.prod
- backend/services/calendar/Dockerfile
- backend/services/calendar/Dockerfile.prod
- backend/services/core/Dockerfile
- backend/services/core/Dockerfile.prod
- backend/services/file-handler/Dockerfile
- backend/services/file-handler/Dockerfile.prod
- backend/services/news/Dockerfile
- backend/services/news/Dockerfile.prod
> bugfix(#328): Use graphQL health check instead of HTTP

- README.md
> misc(#189): switch from docker-compose to docker compose

- docker-compose.prod.yml
- docker-compose.yml
> bugfix(#55): Remove persistent storage from dev db

- docker-compose.deploy.yml
> feature(#332): Adds meilisearch to deploy compose

- frontend/components/Footer/index.tsx
- frontend/components/Header/index.tsx
- frontend/components/layout.tsx
- frontend/package-lock.json
- frontend/package.json
> Fix Layout Alignment

- .github/workflows/migrations.migrator.yml
- backend/migrator/migrations/20211121150000_create-tables.js
- backend/migrator/package.json
- backend/migrator/tests/migrations.spec.js
Add tests for migrations and fix broken 'down' migrations
> build: Add test for migrations

- .eslintrc.json
- backend/migrator/migrations/20220102185300_add_article_mandate_field.js
- backend/migrator/seeds/data.js
- backend/services/core/src/datasources/Mandate.ts
- backend/services/core/src/resolvers.ts
- backend/services/news/graphql.schema.json
- backend/services/news/src/datasources/News.ts
- backend/services/news/src/schema.graphql
- backend/services/news/src/types/database.ts
- backend/services/news/src/types/graphql.ts
- backend/services/news/tests/news.spec.ts
- backend/services/news/tests/queries.spec.ts
- dev.sh
- frontend/api/news.graphql
- frontend/components/Navigation/ListItemSet.tsx
- frontend/components/News/articleSet.tsx
- frontend/functions/authorFunctions.ts
- frontend/generated/graphql.tsx
- frontend/pages/news/article/[id]/index.tsx
- package.json
> feature(#299): Allow for either Member or Mandate as author for articles

- frontend/components/Positions/Position.tsx
- frontend/pages/mandates/[year].tsx
> Fix some styling for committee pages

- backend/services/core/graphql.schema.json
- backend/services/core/src/datasources/Mandate.ts
- backend/services/core/src/resolvers.ts
- backend/services/core/src/schema.graphql
- backend/services/core/src/types/graphql.ts
- backend/services/core/tests/mandate.spec.ts
> feature(#313): Add mandates field to member

- backend/shared/package-lock.json
- backend/shared/package.json
- docker-compose.deploy.yml
- docker-compose.yml
- frontend/package-lock.json
- frontend/package.json
Fixes meilisearch not working by updating it's docker version and sdk versions
> Fixes meilisearch

- frontend/components/Footer/index.tsx
- frontend/components/layout.tsx
Fixes footer placement so it always stays at the bottom of the screen.
> Fixes footer placement

- frontend/components/Calendar/BigCalendar/Toolbar.tsx
- frontend/pages/calendar/index.tsx
- frontend/public/locales/en/calendar.json
- frontend/public/locales/sv/calendar.json
> feature(#367): Changes the subscribes for calendar

- frontend/pages/apis/[policy]/edit.tsx
- frontend/pages/doors/[doorName]/edit.tsx
> #426 Remove cache on doors

- backend/services/booking/src/datasources/BookingRequest.ts
- frontend/api/booking.graphql
- frontend/components/BookingTable/bookingTableModifedStatusCell.tsx
- frontend/components/BookingTable/bookingTableRow.tsx
- frontend/generated/graphql.tsx
- frontend/public/locales/en/booking.json
- frontend/public/locales/sv/booking.json
> #370 Remove booking requests functionality

- frontend/components/FileBrowser/UploadModal.tsx
- frontend/components/Header/AuthenticationStatus.tsx
- frontend/public/locales/en/common.json
- frontend/public/locales/sv/common.json
> Various fixes

- backend/migrator/seeds/data.js
- backend/services/calendar/src/datasources/Events.ts
- backend/services/core/src/datasources/Committee.ts
- backend/services/core/src/datasources/Member.ts
- backend/services/news/src/datasources/News.ts
- backend/shared/src/database.ts
- frontend/api/events.graphql
- frontend/components/ArticleEditor/index.tsx
- frontend/components/Calendar/EventCard.tsx
- frontend/components/Calendar/EventEditor.tsx
- frontend/components/Calendar/EventPage.tsx
- frontend/components/Documents/index.tsx
- frontend/components/News/article.tsx
- frontend/functions/authorFunctions.ts
- frontend/generated/graphql.tsx
- frontend/pages/news/article/[id]/edit.tsx
> #271 Edit user content

- frontend/components/FileBrowser/index.tsx
- frontend/components/FileBrowser/useFileActionHandler.tsx
- frontend/components/Navigation/navigationItems.tsx
- frontend/pages/documents/policy.tsx
- frontend/pages/documents/srd.tsx
- frontend/public/locales/en/common.json
- frontend/public/locales/sv/common.json
- frontend/routes.ts
> Add srd and policy pages

- frontend/functions/memberFunctions.ts
P.S. this is untested, I do not have a working test environment set up.
> Fix double spacing in members full names with no nickname (#494)

- frontend/components/Navigation/navigationItems.tsx
- frontend/pages/documents/policy.tsx
- frontend/public/locales/en/common.json
- frontend/public/locales/sv/common.json
This fixes #525. 
(Again, I haven't tested this since I have no working test-environment.)
> Fix titling of the Policy-page

- frontend/components/Header/AuthenticationStatus.tsx
> #484 Register button fixed 

- build-details.md
- frontend/components/Positions/Mandate.tsx
> (#490) Fix mandate styling 

- backend/services/core/Dockerfile
- backend/services/core/graphql.schema.json
- backend/services/core/seeds/api_access_policies.ts
- backend/services/core/src/datasources.ts
- backend/services/core/src/datasources/AdminAPI.ts
- backend/services/core/src/datasources/Mandate.ts
- backend/services/core/src/datasources/Member.ts
- backend/services/core/src/resolvers/coreResolvers.ts
- backend/services/core/src/schemas/booking.graphql
- backend/services/core/src/schemas/core.graphql
- backend/services/core/src/types/graphql.ts
- build-details.md
- dev.sh
- frontend/Dockerfile
- frontend/api/admin.graphql
- frontend/components/Navigation/Menu.tsx
- frontend/functions/handleApolloError.ts
- frontend/generated/graphql.tsx
- frontend/pages/admin.tsx
This also adds the ability to seed from the admin panel.
> :bug: Fix bug where picture_path is not indexed if done manually

- backend/services/core/graphql.schema.json
- backend/services/core/src/datasources/News.ts
- backend/services/core/src/resolvers/newsResolvers.ts
- backend/services/core/src/schemas/news.graphql
- backend/services/core/src/server.ts
- backend/services/core/src/types/graphql.ts
- backend/services/core/src/types/news.ts
- backend/services/core/tests/news/news.spec.ts
- frontend/api/news.graphql
- frontend/codegen.yml
- frontend/components/ArticleEditor/ArticleEditorItem/index.tsx
- frontend/components/Calendar/EventEditor.tsx
- frontend/components/News/article.tsx
- frontend/components/News/articleStyles.ts
- frontend/generated/graphql.tsx
- frontend/package-lock.json
- frontend/package.json
- frontend/pages/news/article/[id]/edit.tsx
- frontend/pages/news/article/create.tsx
- frontend/public/locales/en/common.json
- frontend/public/locales/en/news.json
- frontend/public/locales/sv/news.json
> ✨ Images in markdown and news

- frontend/components/Committees/CommitteesList.tsx
> :lipstick: Fixed Committee width not working on mobile

- frontend/components/TV/TVWrapper.tsx
> :bug: Fixed bug where the browser wouldn't properly autoscroll 

- frontend/components/Navigation/NavigationList.tsx
> :sparkles: Menu now closes on route change

- frontend/components/Documents/index.tsx
- frontend/components/Social/CommentButton.tsx
- frontend/components/Social/LikeButton.tsx
- frontend/pages/booking/index.tsx
- frontend/public/locales/en/booking.json
- frontend/public/locales/en/common.json
- frontend/public/locales/en/fileBrowser.json
- frontend/public/locales/sv/booking.json
- frontend/public/locales/sv/common.json
- frontend/public/locales/sv/fileBrowser.json
> :globe_with_meridians: Add translations and fix like/unlike button

- frontend/components/Calendar/BigCalendar/index.tsx
- frontend/components/Calendar/index.tsx
- frontend/components/Link.tsx
- frontend/components/Mandates/MandateSet.tsx
- frontend/components/News/article.tsx
- frontend/components/News/articleStyles.ts
- frontend/components/Positions/index.tsx
- frontend/components/Social/SocialButton/LikeButton.tsx
- frontend/components/Social/SocialButton/SocialButton.tsx
- frontend/hooks/useCommittees.ts
- frontend/pages/calendar/tv.tsx
- frontend/public/locales/en/common.json
- frontend/public/locales/sv/common.json
Closes #634 
Closes #632 
Closes #625 
Closes #627 
Closes #626 
Closes #607 
Closes #610
> 🐛  Bug fixes

- backend/services/core/graphql.schema.json
- backend/services/core/migrations/20221114234337_event_comments.ts
- backend/services/core/seeds/api_access_policies.ts
- backend/services/core/seeds/data.ts
- backend/services/core/src/datasources/Events.ts
- backend/services/core/src/resolvers/eventResolvers.ts
- backend/services/core/src/schemas/events.graphql
- backend/services/core/src/shared/converters.ts
- backend/services/core/src/types/events.ts
- backend/services/core/src/types/graphql.ts
- backend/services/core/tests/calendar/event.spec.ts
- backend/services/core/tests/calendar/mutations.spec.ts
- backend/services/core/tests/calendar/queries.spec.ts
- frontend/api/events.graphql
- frontend/components/Calendar/EventPage.tsx
- frontend/components/News/article.tsx
- frontend/components/Social/Comments/Comment.tsx
- frontend/components/Social/Comments/CommentField.tsx
- frontend/components/Social/Comments/Comments.tsx
- frontend/components/Social/Comments/DeleteComment.tsx
- frontend/generated/graphql.tsx
- frontend/pages/booking/index.tsx
> ✨  Event comments

- backend/services/core/src/server.ts
> :loud_sound: Add logging to mutations

- backend/services/core/src/datasources/Mandate.ts
- frontend/components/Header/SearchInput.tsx
- frontend/components/Members/MembersSelector.tsx
> :bug: Don't remove mandates with duplicates from keycloak

- backend/services/core/graphql.schema.json
- backend/services/core/migrations/20221115081839_bookables-type-door.ts
- backend/services/core/seeds/data.ts
- backend/services/core/src/datasources.ts
- backend/services/core/src/datasources/Access.ts
- backend/services/core/src/datasources/BookingRequest.ts
- backend/services/core/src/migrator/tests/migrations.spec.ts
- backend/services/core/src/resolvers/bookingResolvers.ts
- backend/services/core/src/schemas/booking.graphql
- backend/services/core/src/types/booking.ts
- backend/services/core/src/types/graphql.ts
- backend/services/core/tests/booking/bookingRequest.spec.ts
- frontend/api/booking.graphql
- frontend/codegen.yml
- frontend/components/Bookables/BookableRow.tsx
- frontend/generated/graphql.tsx
- frontend/pages/booking/bookables/[id]/index.tsx
- frontend/pages/booking/bookables/index.tsx
- frontend/providers/GraphQLProvider.tsx
> ✨ Accept booking with access

- frontend/components/ArticleEditor/TagSelector/index.tsx
- frontend/components/News/NewsFilter.tsx
- frontend/components/Tag.tsx
- frontend/generated/graphql.tsx
> 💄 Change tag editor to use removable chips

- backend/services/core/graphql.schema.json
- backend/services/core/src/datasources/News.ts
- backend/services/core/src/resolvers/newsResolvers.ts
- backend/services/core/src/schemas/news.graphql
- backend/services/core/src/types/graphql.ts
- frontend/api/news.graphql
- frontend/components/ArticleEditor/TagSelector/index.tsx
- frontend/components/ArticleEditor/index.tsx
- frontend/components/News/NewsFilter.tsx
- frontend/components/News/NewsPage.tsx
- frontend/components/News/article.tsx
- frontend/components/News/articleSet.tsx
- frontend/generated/graphql.tsx
- frontend/pages/index.tsx
> :sparkles: Filter news on tags

- backend/services/core/graphql.schema.json
- backend/services/core/package-lock.json
- backend/services/core/package.json
- backend/services/core/src/datasources/News.ts
- backend/services/core/src/keycloak.ts
- backend/services/core/src/schemas/news.graphql
- backend/services/core/src/types/graphql.ts
Closes #666 
Closes #664 
Closes #662
> 🐛  Tag bugs

- frontend/components/FileBrowser/index.tsx
- frontend/components/Navigation/Menu.tsx
- frontend/pages/documents/kravprofiler.tsx
- frontend/public/locales/en/common.json
- frontend/public/locales/sv/common.json
- frontend/routes.ts
> :sparkles: Add kravprofiler page

- frontend/.babelrc
- frontend/components/Social/Comments/CommentAmount.tsx
- frontend/components/Social/Likers/Likers.tsx
- frontend/components/Social/SocialButton/SocialButton.tsx
> 🐛 #681 Fixed comment and like color in safari

- backend/services/core/graphql.schema.json
- backend/services/core/migrations/20221117150454_event_larm_active.ts
- backend/services/core/src/datasources/Events.ts
- backend/services/core/src/resolvers/eventResolvers.ts
- backend/services/core/src/schemas/events.graphql
- backend/services/core/src/shared/converters.ts
- backend/services/core/src/types/events.ts
- backend/services/core/src/types/graphql.ts
- backend/services/core/tests/calendar/event.spec.ts
- frontend/api/events.graphql
- frontend/components/Calendar/EventEditor.tsx
- frontend/generated/graphql.tsx
- frontend/pages/api/door-larmed.ts
- frontend/public/locales/en/event.json
- frontend/public/locales/sv/event.json
> :sparkles: Alarm door for events

- backend/services/core/src/datasources/AdminAPI.ts
- backend/services/core/src/datasources/Events.ts
- backend/services/core/src/datasources/News.ts
- backend/services/core/src/index.ts
- backend/services/core/src/migrator/migrator.ts
- backend/services/core/src/migrator/searchData.ts
- backend/services/core/src/shared/adminUtils.ts
- frontend/components/Calendar/BigCalendarDay.tsx
- frontend/components/Calendar/EventSearchInput.tsx
- frontend/components/News/ArticleSearchInput.tsx
- frontend/components/News/NewsPage.tsx
- frontend/package-lock.json
- frontend/package.json
- frontend/pages/api/searcharticles.ts
- frontend/pages/api/searchevents.ts
- frontend/pages/events/index.tsx
- frontend/pages/events/passed.tsx
- frontend/pages/index.tsx
- frontend/public/locales/en/event.json
- frontend/public/locales/en/news.json
- frontend/public/locales/sv/event.json
- frontend/public/locales/sv/news.json
- frontend/routes.ts
- frontend/types/ArticleHit.ts
- frontend/types/EventHit.ts
> :sparkles: Implement search on events and news

- frontend/.babelrc
- frontend/pages/booking/bookables/index.tsx
- frontend/public/locales/en/booking.json
- frontend/public/locales/sv/booking.json
> 🌐 #619 Translated-bookings-page 

- frontend/providers/ThemeProvider.tsx
> :lipstick: Set default color mode to dark

- frontend/components/News/article.tsx
- frontend/components/Social/Comments/Comment.tsx
- frontend/functions/datetimeFunctions.ts
- package-lock.json
> 🌐 713 time translation fixed

- frontend/components/Calendar/EventPage.tsx
> 💄 Fix styling of event links

- frontend/pages/members/[id]/edit.tsx
Goes back to profile after edit profile update button is clicked
> ✨  #710 go back to profile

- backend/services/core/graphql.schema.json
- backend/services/core/migrations/20221126095714_position_description.ts
- backend/services/core/seeds/data.ts
- backend/services/core/src/schemas/core.graphql
- backend/services/core/src/shared/converters.ts
- backend/services/core/src/types/database.ts
- backend/services/core/src/types/graphql.ts
- backend/services/core/tests/core/mandate.spec.ts
- backend/services/core/tests/core/position.spec.ts
- frontend/api/positions.graphql
- frontend/components/Positions/Position.tsx
- frontend/generated/graphql.tsx
> :sparkles: Add description to positions

- backend/services/core/seeds/helpers/insertMembers.ts
- backend/services/core/src/datasources/Events.ts
- backend/services/core/src/datasources/Notifications.ts
#311 
We still have to send out notifications on mobile when new events are published.
> :sparkles: Send onsite-notifications for certain event happenings

- backend/services/core/graphql.schema.json
- backend/services/core/seeds/helpers/insertMembers.ts
- backend/services/core/src/datasources/Files.ts
- backend/services/core/src/resolvers/fileResolvers.ts
- backend/services/core/src/schemas/file.graphql
- backend/services/core/src/types/graphql.ts
- backend/services/core/tests/core/access.spec.ts
- backend/services/core/tests/file-handler/files.spec.ts
- frontend/api/files.graphql
- frontend/generated/graphql.tsx
- frontend/pages/members/[id]/change-profile-picture.tsx
> :sparkles: Make sure peoples profile pictures can be deleted

- dev.sh
- frontend/components/AddAccessPolicyForm.tsx
- frontend/components/Header/SearchInput.tsx
- frontend/components/MemberEditor/index.tsx
- frontend/components/Members/Member.tsx
- frontend/components/Social/Comments/Comment.tsx
- frontend/components/Social/Comments/CommentField.tsx
- frontend/components/Social/Likers/Likers.tsx
- frontend/components/Social/MemberSignature.tsx
- frontend/components/Social/PeopleGoing/PeopleGoing.tsx
- frontend/components/Social/PeopleInterested/PeopleInterested.tsx
- frontend/functions/memberFunctions.ts
- frontend/pages/api/boss.ts
- frontend/pages/api/search.ts
- frontend/pages/mojt/boss.tsx
- package-lock.json
> :children_crossing: Improve UX of apis admin

- backend/services/core/tests/keycloak/data.ts
- frontend/next.config.js
> :bricks: Rewrite /salto to /api/door

- frontend/components/Documents/index.tsx
> :bug: Make sure document chips wrap

- frontend/components/Calendar/index.tsx
> :bug: Fix issue with calendar date range

- frontend/components/Bookables/BookableRow.tsx
- frontend/components/Tags/NewsTagItem.tsx
- frontend/pages/booking/bookables/index.tsx
- frontend/pages/news/admin/tags/index.tsx
> 💄   854 fix mobile view on some pages

- frontend/components/Documents/Meeting.tsx
- frontend/styles/globals.css
> 🐛  Fix links overflowing

- frontend/next.config.js
- frontend/pages/documents/index.tsx
- frontend/routes.ts
Added redirects (in English and Swedish) to the Github download pages for our reglemente and stadgar.
> ✨ 974 dsek.se/stadgar and dsek.se/reglemente

- backend/services/core/graphql.schema.json
- backend/services/core/src/datasources/Position.ts
- backend/services/core/src/schemas/core.graphql
- backend/services/core/src/shared/converters/index.ts
- backend/services/core/src/types/graphql.ts
- frontend/api/positions.graphql
- frontend/components/Positions/index.tsx
- frontend/generated/graphql.tsx
- frontend/hooks/usePositionsByCommittee.ts
> :sparkles: Committee by year

- frontend/components/News/articleStyles.ts
- frontend/providers/ThemeProvider.tsx
> :lipstick: fix inconsistent use of border radius

- frontend/pages/_app.tsx
In native app, user's could zoom on pages which was kind of weird. This PR disables that, just for the native app.
> Fix app zoom

- backend/services/core/src/datasources/BookingRequest.ts
- backend/services/core/src/datasources/Mandate.ts
- backend/services/core/tests/booking/bookingRequest.spec.ts
- backend/services/core/tests/booking/data.ts
- frontend/components/Bookables/BookableRow.tsx
- frontend/components/BookingFilter/index.tsx
- frontend/components/Documents/index.tsx
- frontend/components/FileBrowser/index.tsx
- frontend/components/Header/components/LanguageSelector.tsx
- frontend/components/Header/components/MyCart.tsx
- frontend/components/Header/index.tsx
- frontend/components/Home/DisplayMeeting.tsx
- frontend/components/News/article.tsx
- frontend/components/Social/Comments/Comments.tsx
- frontend/components/Songs/SongsList.tsx
- frontend/components/TV/TVWrapper.tsx
- frontend/pages/apis/[policy]/edit.tsx
- frontend/pages/booking/bookables/index.tsx
- frontend/pages/booking/index.tsx
- frontend/pages/members/[id]/change-profile-picture.tsx
- frontend/providers/ThemeProvider.tsx
- frontend/providers/UserProvider.tsx
- frontend/public/locales/sv/common.json
- frontend/public/locales/sv/homePage.json
- frontend/routes.ts
Closes #896
Closes #918 
Closes #833 
Closes #860 ? (depends on what the issue actually meant, but you CAN see bookings from the past now)
A whole lot of smaller fixes which would just take a lot of time to split up into multiple PRs.
> :bug: Multiple minor fixes

- frontend/functions/colorFunctions.ts
> :bug: Fix issue when color is undefined or not a correct color

- frontend/next.config.js
- frontend/public/.well-known/apple-app-site-association
- frontend/public/.well-known/assetlinks.json
> ✨ Deep linking for app

- frontend/components/Documents/proccessFilesData.ts
> :bug: Fix bug where VTM/VTM-extra are filtered together

- frontend/components/Members/Member.tsx
> :sparkles: Show mandate period on member's profile on hover

- frontend/components/BookingTable/bookingTableRow.tsx
> :bug: Fix issue where consecutive bookings where marked as conflicting

- frontend/components/FileBrowser/index.tsx
> :bug: No error message when missing permission to rename

- frontend/components/News/NewsPage.tsx
- frontend/pages/news/article/[id]/edit.tsx
- frontend/pages/news/article/create.tsx
> :bug: Reload articles after a new one has been created

- backend/services/core/src/datasources/Events.ts
- backend/services/core/src/datasources/Member.ts
- backend/services/core/src/datasources/News.ts
- backend/services/core/src/resolvers/newsResolvers.ts
- backend/services/core/src/types/graphql.ts
- backend/services/core/tests/calendar/event.spec.ts
> :bug: Fix issue where likers and commentors nicknames were shown

- backend/services/core/src/datasources/Access.ts
- frontend/components/Header/components/Navigation/data.tsx
- frontend/pages/booking/bookables/[id]/index.tsx
- frontend/pages/booking/bookables/create.tsx
- frontend/pages/booking/bookables/index.tsx
- frontend/pages/doors/[doorName]/edit.tsx
- frontend/pages/doors/edit.tsx
Mostly ui changes but it also used the wrong access policy in the backend for changes
> :bug: Fix access for door apis

- backend/services/core/graphql.schema.json
- backend/services/core/migrations/20230525133525_add_ping_table.ts
- backend/services/core/seeds/helpers/insertApiAccessPolicies.ts
- backend/services/core/src/datasources/Member.ts
- backend/services/core/src/datasources/Notifications.ts
- backend/services/core/src/resolvers/coreResolvers.ts
- backend/services/core/src/schemas/core.graphql
- backend/services/core/src/types/database.ts
- backend/services/core/src/types/graphql.ts
- backend/services/core/tests/core/member.spec.ts
- frontend/api/members.graphql
- frontend/api/pings.graphql
- frontend/components/Members/Member.tsx
- frontend/components/Ping/PingCard.tsx
- frontend/generated/graphql.tsx
- frontend/pages/members/[id]/index.tsx
- frontend/pages/pings/index.tsx
- frontend/public/locales/en/member.json
- frontend/public/locales/sv/member.json
- frontend/routes.ts
> ✨ 1138 add poke puffa functionality

- backend/services/core/seeds/helpers/insertApiAccessPolicies.ts
- backend/services/core/src/datasources/Mandate.ts
- backend/services/core/src/datasources/Position.ts
- backend/services/core/src/shared/database.ts
- frontend/components/News/articleSet.tsx
- frontend/components/Nolla/Article.tsx
- frontend/components/Nolla/layout.tsx
- frontend/functions/authorFunctions.ts
- frontend/pages/members/[id]/index.tsx
- Stab is no longer hidden for admin
- "Admins" are everyone with any of the roles: ["nolla:admin", "nolla:see_stab", "cora:admin", "admin:settings:update"]
Scroll fixed on nolla pages
> :bug: Fix issues regarding nolla page scroll and hidden stab

- frontend/components/GoverningDocuments/DocumentButton.tsx
> :bug: Make sure that pdf API version and worker version are synced

- frontend/components/Committees/CommitteeIcon.tsx
Fixes https://github.com/Dsek-LTH/member-page/issues/1273
> 💄 Update källarmästeriets icon

- frontend/pages/webshop/checkout.tsx
- frontend/pages/webshop/index.tsx
Add information to comply with Swedbanks requirements.
> :sparkles: Webshop Information
